# Generated by Django 4.2 on 2023-04-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0004_order_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productinfo',
            name='unique_product_info',
        ),
        migrations.RemoveConstraint(
            model_name='productinfoparameter',
            name='unique_product_parameter',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='productinfoparameter',
            name='parameter',
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addressies', to='ordering_service.contact', verbose_name='Контакт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='product_info_parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ordering_service.productinfoparameter', verbose_name='Список параметров'),
            preserve_default=False,
        ),
    ]
