# Generated by Django 4.2 on 2023-04-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0005_remove_productinfo_unique_product_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='product_info_parameter',
        ),
        migrations.AddField(
            model_name='productinfoparameter',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_info_parameters', to='ordering_service.parameter', verbose_name='Название параметра'),
            preserve_default=False,
        ),
    ]
