# Generated by Django 4.2 on 2023-04-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0006_remove_parameter_product_info_parameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Карточка товара', 'verbose_name_plural': 'Карточки товаров'},
        ),
        migrations.AlterField(
            model_name='productinfoparameter',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ordering_service.productinfo', verbose_name='Информация о товаре'),
        ),
        migrations.AddConstraint(
            model_name='productinfoparameter',
            constraint=models.UniqueConstraint(fields=('product_info', 'parameter'), name='unique_product_parameter'),
        ),
    ]
