# Generated by Django 4.2 on 2023-04-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0007_alter_productinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfoparameter',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info_parameters', to='ordering_service.productinfo', verbose_name='Информация о товаре'),
        ),
    ]
