# Generated by Django 4.2 on 2023-05-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_service', '0012_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
